### ISSUE TITLE
[Common] 공용 CSS 생성

### ISSUE THREAD

**Issue by ryudg** [FRONTENDSCHOOL6/react-project-11#21]
### 프로젝트에서 공통으로 사용될 CSS 생성

- [x] global
```css
@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;500;600;700&display=swap');

:root {
  /* Colors */
  --black: #000000;
  --white: #ffffff;
  --gray-100: #e1e1e1;
  --gray-200: #c4c4c4;
  --gray-300: #a6a6a6;
  --gray-400: #898989;
  --gray-500: #6b6b6b;
  --gray-600: #565656;
  --gray-700: #404040;
  --gray-800: #2b2b2b;
  --gray-900: #151515;
  --brand-red-1: #ff153c;
  --brand-red-2: #e93945;
  --brand-dark-bg-1: #191919;
  --brand-dark-bg-2: #212121;

  /* Fonts */
  --heading-medium: 700 16px/140% "Noto Sans KR", sans-serif;
  --heading-large: 700 21.33px/140% "Noto Sans KR", sans-serif;
  --heading-xl: 700 28.43px/140% "Noto Sans KR", sans-serif;
  --heading-xxl: 700 37.9px/140% "Noto Sans KR", sans-serif;
  --heading-xxxl: 700 50.52px/140% "Noto Sans KR", sans-serif;
  --label-small: 600 12px/150% "Noto Sans KR", sans-serif;
  --label-medium: 600 16px/150% "Noto Sans KR", sans-serif;
  --label-large: 600 21.33px/150% "Noto Sans KR", sans-serif;
  --label-xl: 600 28.43px/150% "Noto Sans KR", sans-serif;
  --label-xxl: 600 37.9px/150% "Noto Sans KR", sans-serif;
  --paragraph-small: 400 12px/160% "Noto Sans KR", sans-serif;
  --paragraph-medium: 400 16px/160% "Noto Sans KR", sans-serif;
  --paragraph-large: 400 21.33px/160% "Noto Sans KR", sans-serif;
  --paragraph-xl: 400 28.43px/160% "Noto Sans KR", sans-serif;

  /* Effects */
  --text-box-shadow: inset 1px 1px 0px 0px rgba(0, 0, 0, 1);
  --above-high-box-shadow: 0px -16px 48px 0px rgba(0, 0, 0, 0.3);
  --above-medium-box-shadow: 0px -8px 36px 0px rgba(0, 0, 0, 0.2);
  --above-low-box-shadow: 0px -4px 24px 0px rgba(0, 0, 0, 0.1);
  --below-high-box-shadow: 0px 16px 48px 0px rgba(0, 0, 0, 0.3);
  --below-medium-box-shadow: 0px 8px 36px 0px rgba(0, 0, 0, 0.2);
  --below-low-box-shadow: 0px 4px 24px 0px rgba(0, 0, 0, 0.1);
}
```
- [x] reset
```
html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed, 
figure, figcaption, footer, header, hgroup, 
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
    margin: 0;
    padding: 0;
    border: 0;
    font-size: 100%;
    font: inherit;
    vertical-align: baseline;
}
/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure, 
footer, header, hgroup, menu, nav, section {
    display: block;
}
body {
    line-height: 1;
}
ol, ul {
    list-style: none;
}
blockquote, q {
    quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
    content: '';
    content: none;
}
table {
    border-collapse: collapse;
    border-spacing: 0;
}
```

### 이미지 [ 옵션 ]
![image](https://github.com/FRONTENDSCHOOL6/react-project-11/assets/103430498/e6b31933-51da-413b-9a78-07f2579f0629)

**Comment by ryudg** [comment]
# a11yhidden 클래스 추가
```css
/* Accessibility Styles */
.a11yHidden,
legend {
  overflow: hidden;
  position: absolute !important;
  clip: rect(0, 0, 0, 0);
  clip-path: inset(50%);
  width: 1px;
  height: 1px;
  margin: -1px;
}
```
